kind: Service
apiVersion: v1
metadata:
  name:  travel-web-service
spec:
  selector:
    app:  travel-web
  type:   NodePort
  ports:
  - name: travel-web
    port:  80
    targetPort:  8081
    nodePort: 30007